import "@ui/styles/globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "../components/auth/AuthProvider";
import { ThemeProvider } from "next-themes";
import { getSession } from "next-auth/react";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Web3 To-Do",
  description: "Generated by Mode Mobile",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
